version: "3.8"
services:
  # user-service:
  #   build: ./services/user
  #   env_file:
  #     - .env
  #   depends_on:
  #     - user-db
  #   networks:
  #     - ecommerce-network

  # product-service:
  #   build: ./services/product
  #   env_file:
  #     - .env
  #   depends_on:
  #     - product-db
  #   networks:
  #     - ecommerce-network

  # order-service:
  #   build: ./services/order
  #   env_file:
  #     - .env
  #   depends_on:
  #     - order-db
  #     - rabbitmq
  #   networks:
  #     - ecommerce-network

  # payment-service:
  #   build: ./services/payment
  #   env_file:
  #     - .env
  #   depends_on:
  #     - payment-db
  #     - rabbitmq
  #   networks:
  #     - ecommerce-network

  # gateway-service:
  #   build: ./services/gateway
  #   env_file:
  #     - .env
  #   depends_on:
  #     - rabbitmq
  #   networks:
  #     - ecommerce-network

  rabbitmq:
    image: "rabbitmq:management"
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - ecommerce-network

  user-db:
    image: mongo
    ports:
      - "27017:27017"
    networks:
      - ecommerce-network
    volumes:
      - user:/data/db

  product-db:
    image: mongo
    ports:
      - "27018:27017"
    networks:
      - ecommerce-network
    volumes:
      - product:/data/db

  order-db:
    image: mongo
    ports:
      - "27019:27017"
    networks:
      - ecommerce-network
    volumes:
      - order:/data/db

  payment-db:
    image: mongo
    ports:
      - "27020:27017"
    networks:
      - ecommerce-network
    volumes:
      - payment:/data/db

networks:
  ecommerce-network:
    driver: bridge

volumes:
  payment:
  order:
  user:
  product:
